# Generated by Django 4.2.7 on 2024-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("project_description", models.TextField()),
                ("project_start_date", models.DateField()),
                ("project_end_date", models.DateField()),
            ],
        ),
    ]
