# Generated by Django 4.2.7 on 2024-12-19 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0002_alter_projectmodel_project_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="project_end_date",
            field=models.DateField(default=datetime.date(2024, 12, 19)),
        ),
    ]
