# Generated by Django 4.2.7 on 2024-12-19 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0003_alter_projectmodel_project_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="project_end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
