# Generated by Django 4.2.7 on 2024-12-27 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Project", "0004_alter_projectmodel_project_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
