# Generated by Django 4.2.7 on 2024-12-16 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_alter_users_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
